# Generated by Django 4.2.6 on 2023-10-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('domain', models.URLField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lf.company')),
            ],
        ),
        migrations.CreateModel(
            name='SEOdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_keywords', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lf.company')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('connection', models.ManyToManyField(to='lf.entity')),
                ('topical_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lf.topicalmap')),
            ],
        ),
    ]
