# Generated by Django 4.2.6 on 2023-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0003_company_niche'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
