# Generated by Django 4.2.6 on 2023-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0004_company_domain_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_pages_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
