# Generated by Django 4.2.6 on 2023-10-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0006_company_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='textrazor_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicalmap',
            name='niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lf.niche'),
        ),
        migrations.AlterField(
            model_name='topicalmap',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lf.company'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('textrazor_json', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lf.company')),
            ],
        ),
    ]
