# Generated by Django 4.2.6 on 2023-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0007_entity_textrazor_json_topicalmap_niche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
