# Generated by Django 4.2.6 on 2023-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0008_company_is_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pages_in_serps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='traffic_us',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
