# Generated by Django 4.2.6 on 2023-11-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0010_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lf.marketingcategory'),
        ),
    ]
