# Generated by Django 4.2.6 on 2023-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0011_marketingcategory_portfolioitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
